# Generated by Django 5.0.4 on 2024-04-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='education',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='jobs',
            name='experiance',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='jobs',
            name='website_url',
            field=models.URLField(default=None),
        ),
    ]
