# Generated by Django 5.0.4 on 2024-04-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobs_education_jobs_experiance_jobs_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobrole',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
