# Generated by Django 5.0.4 on 2024-04-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
    ]
